"""Added outbox_event table

Revision ID: 24783f6c3662
Revises: 3c43fc47684f
Create Date: 2026-08-23 19:48:46.213839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24783f6c3662'
down_revision: Union[str, Sequence[str], None] = '3c43fc47684f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aggregate_id_type', 'outbox_event', ['aggregate_id', 'type'], unique=False)
    op.create_index('idx_id', 'outbox_event', ['id'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_id', table_name='outbox_event', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('idx_aggregate_id_type', table_name='outbox_event')
    op.drop_table('outbox_event')
    # ### end Alembic commands ###
